
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpmqoxgmoipcgflimzec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwbXFveGdtb2lwY2dmbGltemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjQ1ODgsImV4cCI6MjA1NzYwMDU4OH0.NogyZtJokkeLthaB-dNw6ZaYsyHkyFcwjsVEiUfDjiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define types for our queries to help with type checking
export type SystemSettings = {
  id: string;
  category: string;
  settings: any;
  created_at: string | null;
  updated_at: string | null;
}

export type UserRole = {
  id: string;
  name: string;
  accessible_pages: string[] | null;
  permissions: {
    full_access?: boolean;
    can_view?: boolean;
    can_edit?: boolean;
    can_delete?: boolean;
  } | null;
  created_at: string | null;
  updated_at: string | null;
}

export type User = {
  id: number;
  username: string | null;
  email: string;
  role: string | null;
  password: string | null;
  created_at: string;
}

export type Venue = {
  id: string;
  name: string;
  description: string | null;
  capacity: number;
  square_footage: number;
  hourly_rate: number;
  availability: string | null;
  image_url: string | null;
  features: string[] | null;
  created_at: string | null;
  updated_at: string | null;
}

export type Client = {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  client_type: string | null;
  address: string | null;
  notes: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type Booking = {
  id: string;
  client_id: string | null;
  venue_id: string | null;
  start_date: string;
  end_date: string;
  guest_count: number;
  total_amount: number | null;
  deposit_amount: number | null;
  deposit_paid: boolean | null;
  created_at: string | null;
  updated_at: string | null;
  event_type: string;
  event_name: string;
  status: string;
  notes: string | null;
}

export type Task = {
  id: string;
  booking_id: string | null;
  title: string;
  description: string | null;
  due_date: string | null;
  assigned_to: string | null;
  status: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type StaffMember = {
  id: string;
  name: string;
  position: string;
  department: string;
  contact: string | null;
  status: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type MenuItem = {
  id: string;
  category_id: string | null;
  name: string;
  description: string | null;
  price: number;
  is_special: boolean | null;
  ingredients: string[] | null;
  image_url: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type MenuCategory = {
  id: string;
  name: string;
  description: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type InventoryItem = {
  id: string;
  name: string;
  category: string;
  quantity: number;
  min_quantity: number | null;
  unit: string | null;
  status: string | null;
  notes: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type Invoice = {
  id: string;
  booking_id: string | null;
  invoice_number: string;
  issue_date: string | null;
  due_date: string;
  amount: number;
  tax_amount: number | null;
  total_amount: number;
  status: string | null;
  notes: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type Payment = {
  id: string;
  invoice_id: string | null;
  amount: number;
  payment_method: string;
  transaction_id: string | null;
  payment_date: string | null;
  notes: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type ClientMessage = {
  id: string;
  client_id: string | null;
  message: string;
  sender: string;
  sent_at: string | null;
  created_at: string | null;
  updated_at: string | null;
}

// New types for our recently created tables
export type UserPreference = {
  user_id: string;
  sidebar_collapsed: boolean;
  updated_at: string;
}

export type DashboardStat = {
  id: string;
  total_revenue: number;
  bookings_this_month: number;
  active_venues: number;
  total_guests_today: number;
  last_updated: string;
}

export type DashboardNotification = {
  id: string;
  title: string;
  description: string;
  time: string;
  is_read: boolean;
  created_at: string;
}

export type StaffStat = {
  id: string;
  total_staff: number;
  available_today: number;
  on_duty: number;
  upcoming_shifts: number;
  last_updated: string;
}

// Type for form submissions to ensure type safety
export type UserRoleInsert = {
  name: string;
  accessible_pages?: string[] | null;
  permissions?: {
    full_access?: boolean;
    can_view?: boolean;
    can_edit?: boolean;
    can_delete?: boolean;
  } | null;
}

export type UserInsert = {
  username: string;
  email: string;
  role: string;
  password: string;
}
