
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpmqoxgmoipcgflimzec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwbXFveGdtb2lwY2dmbGltemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjQ1ODgsImV4cCI6MjA1NzYwMDU4OH0.NogyZtJokkeLthaB-dNw6ZaYsyHkyFcwjsVEiUfDjiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define types for our queries to help with type checking
export type SystemSettings = {
  id: string;
  category: string;
  settings: any;
  created_at: string | null;
  updated_at: string | null;
}

export type UserRole = {
  id: string;
  name: string;
  accessible_pages: string[] | null;
  permissions: {
    full_access?: boolean;
    can_view?: boolean;
    can_edit?: boolean;
    can_delete?: boolean;
  } | null;
  created_at: string | null;
  updated_at: string | null;
}

export type User = {
  id: number;
  username: string | null;
  email: string;
  role: string | null;
  password: string | null;
  created_at: string;
}

// Type for form submissions to ensure type safety
export type UserRoleInsert = {
  name: string;
  accessible_pages?: string[] | null;
  permissions?: {
    full_access?: boolean;
    can_view?: boolean;
    can_edit?: boolean;
    can_delete?: boolean;
  } | null;
}

export type UserInsert = {
  username: string;
  email: string;
  role: string;
  password: string;
}
