// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpmqoxgmoipcgflimzec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwbXFveGdtb2lwY2dmbGltemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjQ1ODgsImV4cCI6MjA1NzYwMDU4OH0.NogyZtJokkeLthaB-dNw6ZaYsyHkyFcwjsVEiUfDjiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);